/**
 * Regenerates lib/legal/generated-default-html.ts from React body components.
 * Run from project root: npx tsx generate-legal-default-html.mts
 */
import * as fs from "node:fs";
import * as path from "node:path";
import { fileURLToPath } from "node:url";

import React from "react";
import { renderToStaticMarkup } from "react-dom/server";

async function main() {
  const LegalBodies = await import("./components/legal/bodies/index.ts");

  const __dirname = path.dirname(fileURLToPath(import.meta.url));
  const root = __dirname;
  const outFile = path.join(root, "lib", "legal", "generated-default-html.ts");

  const privacy = renderToStaticMarkup(React.createElement(LegalBodies.PrivacyDocumentBody));
  const terms = renderToStaticMarkup(React.createElement(LegalBodies.TermsDocumentBody));
  const communication = renderToStaticMarkup(
    React.createElement(LegalBodies.CommunicationDocumentBody)
  );

  const source = `/* eslint-disable */
// Generated by generate-legal-default-html.mts — do not edit by hand.
import type { LegalSlug } from "./slug";

export const GENERATED_DEFAULT_LEGAL_HTML: Record<LegalSlug, string> = {
  privacy: ${JSON.stringify(privacy)},
  terms: ${JSON.stringify(terms)},
  communication: ${JSON.stringify(communication)},
};
`;

  fs.writeFileSync(outFile, source, "utf8");
  console.log("Wrote", outFile);
}

await main();
